receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto
  
  prometheus:
    endpoint: "0.0.0.0:8889"

extensions:
  health_check:

processors:
  batch:

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp/logs]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]